# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 39100f48a82f896a7b35134d7d248407df52148163ab911107ea67312c1d03dc7be3a3778e608e1eb24346c43684f0d32ca16b0c72a921ee369534ba9b690a60

test:
  secret_key_base: 6fc2386a326e4b6494205b939ef98b247c3ac78a36f67acea771d6df96825001464d283654d03edfb0c301111ffbdc91d56a47415cbda4aa45486c55c0bf31b5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
